{
  "openapi": "3.0.0",
  "info": {
    "title": "API de Gestión de Proyectos Scrum",
    "description": "API para registrar, listar, buscar, editar y eliminar usuarios, proyectos y sprints.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:5000"
    }
  ],
  "tags": [
    {
      "name": "Usuario",
      "description": "Todo sobre la gestión de usuarios"
    },
    {
      "name": "Autorizacion",
      "description": "Como iniciar sesion"
    },
    {
      "name": "Proyectos",
      "description": "Todo sobre la gestión de proyectos"
    },
    {
      "name": "Sprint",
      "description": "Todo sobre la gestión de sprints"
    }
  ],
  "paths": {
    "/usuarios/crear": {
      "post": {
        "tags": [
          "Usuario"
        ],
        "summary": "Registrar un nuevo usuario",
        "description": "Este endpoint permite registrar un nuevo usuario en el sistema. Requiere enviar un objeto JSON con los datos del usuario como nombre, apellido, correo, rol y contraseña.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "USU_NOMBRE",
                  "USU_APELLIDO",
                  "USU_CORREO",
                  "USU_ROL",
                  "USU_CONTRASENA"
                ],
                "properties": {
                  "USU_NOMBRE": {
                    "type": "string"
                  },
                  "USU_APELLIDO": {
                    "type": "string"
                  },
                  "USU_CORREO": {
                    "type": "email"
                  },
                  "USU_ROL": {
                    "type": "string"
                  },
                  "USU_CONTRASENA": {
                    "type": "password"
                  }
                },
                "example": {
                  "USU_NOMBRE": "Santiago",
                  "USU_APELLIDO": "Torres",
                  "USU_CORREO": "santi@gmail.com",
                  "USU_ROL": "Scrum Team",
                  "USU_CONTRASENA": "1234"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando que el usuario fue registrado correctamente.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha registrado el usuario"
                  }
                }
              }
            }
          },
          "400": {
            "description": "error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "faltan campos en la peticion: {faltantes}"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflicto: ya existe un recurso con la misma información.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Ya existe un recurso con los mismos datos"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/eliminar/{id}": {
      "delete": {
        "tags": [
          "Usuario"
        ],
        "summary": "Eliminar un usuario por ID",
        "description": "Este endpoint permite eliminar un usuario del sistema utilizando su identificador único (ID). Si el ID proporcionado es válido y corresponde a un usuario existente, se eliminará de forma permanente.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando que el usuario fue eliminado correctamente del sistema.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha eliminado el usuario"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/usuarios/mostrar": {
      "get": {
        "tags": [
          "Usuario"
        ],
        "summary": "Listar todos los usuarios",
        "description": "Este endpoint permite obtener un listado completo de los usuarios registrados en el sistema. La respuesta incluye información básica como nombre, apellido, correo, rol y contraseña.",
        "responses": {
          "200": {
            "description": "Respuesta exitosa que contiene la lista de usuarios.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "USU_NOMBRE": {
                        "type": "string"
                      },
                      "USU_APELLIDO": {
                        "type": "string"
                      },
                      "USU_CORREO": {
                        "type": "string"
                      },
                      "USU_ROL": {
                        "type": "string"
                      },
                      "USU_CONTRASENA": {
                        "type": "password"
                      }
                    },
                    "example": {
                      "USU_NOMBRE": "Santiago",
                      "USU_APELLIDO": "Torres",
                      "USU_CORREO": "santi@gmail.com",
                      "USU_ROL": "Scrum Team",
                      "USU_CONTRASENA": "1234"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/usuarios/editar/{id}": {
      "put": {
        "tags": [
          "Usuario"
        ],
        "summary": "Editar un usuario por ID",
        "description": "Este endpoint permite editar un usuario del sistema utilizando su identificador único (ID). Si el ID proporcionado es válido y corresponde a un usuario existente, se editara.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando que el usuario fue editado correctamente.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha actualizado el usuario"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflicto: ya existe un recurso con la misma información.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Ya existe un recurso con los mismos datos"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "USU_NOMBRE",
                  "USU_APELLIDO",
                  "USU_CORREO",
                  "USU_ROL",
                  "USU_CONTRASENA"
                ],
                "properties": {
                  "USU_NOMBRE": {
                    "type": "string"
                  },
                  "USU_APELLIDO": {
                    "type": "string"
                  },
                  "USU_CORREO": {
                    "type": "string",
                    "format": "email"
                  },
                  "USU_ROL": {
                    "type": "string"
                  },
                  "USU_CONTRASENA": {
                    "type": "string",
                    "format": "password"
                  }
                },
                "example": {
                  "USU_NOMBRE": "Nombre editado",
                  "USU_APELLIDO": "Apellido editado",
                  "USU_CORREO": "nuevo@gmail.com",
                  "USU_ROL": "Product Owner",
                  "USU_CONTRASENA": "nueva_clave"
                }
              }
            }
          }
        }
      }
    },
    "/proyectos/crear": {
      "post": {
        "tags": [
          "Proyectos"
        ],
        "summary": "Registrar un nuevo proyecto",
        "description": "Este endpoint permite registrar un nuevo proyecto en el sistema. Requiere enviar un objeto JSON con los datos del proyecto como: nombre del proyecto y descripcion del proyecto.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "PROY_NOMBRE",
                  "PROY_DESCRIPCION",
                  "PROY_USU_ID"
                ],
                "properties": {
                  "PROY_NOMBRE": {
                    "type": "string"
                  },
                  "PROY_DESCRIPCION": {
                    "type": "string"
                  },
                  "PROY_USU_ID": {
                    "type": "integer"
                  }
                },
                "example": {
                  "PROY_NOMBRE": " Proyecto x",
                  "PROY_DESCRIPCION": "X proyecto se encarga de...",
                  "PROY_USU_ID": 1
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando que el proyecto fue registrado correctamente.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha registrado el proyecto"
                  }
                }
              }
            }
          },
          "400": {
            "description": "error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "faltan campos en la peticion: {faltantes}"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflicto: ya existe un recurso con la misma información.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Ya existe un recurso con los mismos datos"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/proyectos/eliminar/{id}": {
      "delete": {
        "tags": [
          "Proyectos"
        ],
        "summary": "Eliminar un proyecto por ID",
        "description": "Este endpoint permite eliminar un proyecto del sistema utilizando su identificador único (ID). Si el ID proporcionado es válido y corresponde a un proyecto existente, se eliminará de forma permanente.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando que el proyecto fue eliminado correctamente del sistema.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha eliminado el proyecto"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Proyecto no encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Proyecto no encontrado"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/proyectos/mostrar": {
      "get": {
        "tags": [
          "Proyectos"
        ],
        "summary": "Listar todos los proyectos",
        "description": "Este endpoint permite obtener un listado completo de los proyectos registrados en el sistema. La respuesta incluye información básica como nombre del proyecto y descripcion del proyecto.",
        "responses": {
          "200": {
            "description": "Respuesta exitosa que contiene la lista de proyectos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "PROY_NOMBRE": {
                        "type": "string"
                      },
                      "PROY_DESCRIPCION": {
                        "type": "string"
                      }
                    },
                    "example": {
                      "PROY_NOMBRE": " Proyecto x",
                      "PROY_DESCRIPCION": "X proyecto se encarga de..."
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/proyectos/editar/{id}": {
      "put": {
        "tags": [
          "Proyectos"
        ],
        "summary": "Editar un proyecto por ID",
        "description": "Este endpoint permite editar un proyecto del sistema utilizando su identificador único (ID).",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "PROY_NOMBRE",
                  "PROY_DESCRIPCION"
                ],
                "properties": {
                  "PROY_NOMBRE": {
                    "type": "string"
                  },
                  "PROY_DESCRIPCION": {
                    "type": "string"
                  }
                },
                "example": {
                  "PROY_NOMBRE": "Proyecto actualizado",
                  "PROY_DESCRIPCION": "Este es el nuevo contenido del proyecto"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Proyecto actualizado correctamente.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha actualizado el proyecto"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflicto: ya existe un recurso con la misma información.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Ya existe un recurso con los mismos datos"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/sprints/crear": {
      "post": {
        "tags": [
          "Sprint"
        ],
        "summary": "Registrar un nuevo sprint",
        "description": "Este endpoint permite registrar un nuevo sprint en el sistema. Requiere enviar un objeto JSON con los datos del sprint como: nombre del sprint y descripcion del sprint.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "SPR_FCH_INICIO",
                  "SPR_FCH_FIN",
                  "SPR_OBJETIVO",
                  "SPR_PROY_ID"
                ],
                "properties": {
                  "SPR_FCH_INICIO": {
                    "type": "date"
                  },
                  "SPR_FCH_FIN": {
                    "type": "date"
                  },
                  "SPR_OBJETIVO": {
                    "type": "string"
                  },
                  "SPR_PROY_ID": {
                    "type": "integer"
                  }
                },
                "example": {
                  "SPR_FCH_INICIO": "2025-06-09",
                  "SPR_FCH_FIN": "2025-07-09",
                  "SPR_OBJETIVO": " xx-xx",
                  "SPR_PROY_ID": 1
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando que el sprint fue registrado correctamente.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha registrado el sprint"
                  }
                }
              }
            }
          },
          "400": {
            "description": "error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "faltan campos en la peticion: {faltantes}"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflicto: ya existe un recurso con la misma información.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Ya existe un recurso con los mismos datos"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/sprints/eliminar/{id}": {
      "delete": {
        "tags": [
          "Sprint"
        ],
        "summary": "Eliminar un sprint por ID",
        "description": "Este endpoint permite eliminar un sprint del sistema utilizando su identificador único (ID). Si el ID proporcionado es válido y corresponde a un sprint existente, se eliminará de forma permanente.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando que el sprint fue eliminado correctamente del sistema.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha eliminado el sprint"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Sprint no encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Sprint no encontrado"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/sprints/mostrar": {
      "get": {
        "tags": [
          "Sprint"
        ],
        "summary": "Listar todos los sprints",
        "description": "Este endpoint permite obtener un listado completo de los sprints registrados en el sistema. La respuesta incluye información básica como nombre del sprint y descripcion del sprint.",
        "responses": {
          "200": {
            "description": "Respuesta exitosa que contiene la lista de sprints.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "SPR_FCH_INICIO": {
                        "type": "date"
                      },
                      "SPR_FCH_FIN": {
                        "type": "date"
                      },
                      "SPR_OBJETIVO": {
                        "type": "string"
                      }
                    },
                    "example": {
                      "SPR_FCH_INICIO": "2025-06-09",
                      "SPR_FCH_FIN": "2025-07-09",
                      "SPR_OBJETIVO": " xx-xx"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/sprints/editar/{id}": {
      "put": {
        "tags": [
          "Sprint"
        ],
        "summary": "Editar un sprint por ID",
        "description": "Este endpoint permite editar un sprint del sistema utilizando su identificador único (ID).",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "SPR_FCH_INICIO",
                  "SPR_FCH_FIN",
                  "SPR_OBJETIVO"
                ],
                "properties": {
                  "SPR_FCH_INICIO": {
                    "type": "string",
                    "format": "date"
                  },
                  "SPR_FCH_FIN": {
                    "type": "string",
                    "format": "date"
                  },
                  "SPR_OBJETIVO": {
                    "type": "string"
                  }
                },
                "example": {
                  "SPR_FCH_INICIO": "2025-07-01",
                  "SPR_FCH_FIN": "2025-07-15",
                  "SPR_OBJETIVO": "Objetivo actualizado del sprint"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sprint actualizado correctamente.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Se ha actualizado el sprint"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflicto: ya existe un recurso con la misma información.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "Ya existe un recurso con los mismos datos"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/auth/": {
      "post": {
        "tags": [
          "Autorizacion"
        ],
        "summary": "Autorizar al usuario",
        "description": "Este endpoint autorizar al usuario la entrada al sistema. Requiere enviar un objeto JSON con los datos del proyecto como: usuario y contraseña.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "USU_CORREO",
                  "USU_CONTRASENA"
                ],
                "properties": {
                  "USU_CORREO": {
                    "type": "string"
                  },
                  "USU_CONTRASENA": {
                    "type": "password"
                  }
                },
                "example": {
                  "USU_CORREO": "santi@gmail.com",
                  "USU_CONTRASENA": "1234"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Devuelve un mensaje de confirmación indicando el token de autorizacion.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "(Token)"
                  }
                }
              }
            }
          },
          "400": {
            "description": "error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "mensaje": "faltan campos en la peticion: {faltantes}"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
}